mv -i  ex_implications.fcl \
  ex_implications2.fcl \
  and_or.fcl \
  diff_comps2.fcl \
  diff_comps.fcl \
  ex_implications2.fcl \
  ex_implications.fcl \
  lemmas1.fcl \
  lemmas2_1.fcl \
  lemmas3.fcl \
  lemmas4.fcl \
  lemmas5.fcl \
  lemmas.fcl \
  or_id_com1.fcl \
  or_id_com2.fcl \
  or_id_com_good.fcl \
  or_id_com_shortest.fcl \
  same_comps.fcl \
  signal2.fcl \
  signal3.fcl \
  tree_mirror1.fcl \
  tree_mirror2bis.fcl \
  tree_mirror2.fcl \
  tree_mirror.fcl \
  zero1.fcl \
  zero2.fcl \
  zero3.fcl \
  lemmas2.fcl \
  lemmas5_2.fcl \
  or_id_com3.fcl \
  or_id_com.fcl \
  signal1.fcl \
../unitary_tests